### ISSUE TITLE
Busco 5 incompatibilities

### ISSUE THREAD

**Issue by jannafierst** [esolares/HapSolo#4]
Hi,

I'm trying to run HapSolo and I was able to generate the blat and busco/quast files with busco v. 5. I know you recommend busco v. 3 but I can't get a stable install. The main difference in hapsolo.py seems to be the location of the files/names. I can edit the python script to point towards the v. 5 output, are there other differences I should look out for? Thanks!

**Comment by esolares** [comment]
Hi,

Running BUSCO V4 or V5 will lead to miss-classification of BUSCOs and affect the minimization algorithm for purging of althaps in the genome. This is due to new labeling introduced by the BUSCO developers. This is why HapSolo requires BUSCO V3. I hope to update HapSolo to include support for newer versions of BUSCO.

I hope this helps.

Thank you,

Edwin
